AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: yellcop CF template

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: A lambda that audits the sig-yelling channel
      Runtime: go1.x
      Handler: yellcop
      CodeUri: yellcop.zip
      Tracing: Active
      Timeout: 10
      FunctionUrlConfig:
        AuthType: NONE
        # Cors:
        #   AllowMethods:
        #     - POST
        #   AllowHeaders:
        #     - 
      ReservedConcurrentExecutions: 1
      Role:
        Fn::GetAtt: FunctionRole.Arn

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Function}"
      RetentionInDays: 7

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ['lambda.amazonaws.com']
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: yellcop-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:DescribeParameters
                  - ssm:PutParameter
                Resource: '*'

SlackVerificationToken:
  Type: AWS::SSM::Parameter
  Properties:
    Description: yellcop slack token
    Type: String
    Name: /yellcop/tokens/slack/verification-token
    Value:
WarningsExtra:
  Type: AWS::SSM::Parameter
  Properties:
    Description: yellcop warnings
    Type: String
    Name: /yellcop/warnings
    Value:
FailuresExtra:
  Type: AWS::SSM::Parameter
  Properties:
    Description: yellcop failures
    Type: String
    Name: /yellcop/failures
    Value:

Events:
  MyApi:
    Type: Api
    Properties:
      Path: /prood
      Method: POST

Events:
  MyApi:
    Type: Api
    Properties:
      Path: /
      Method: POST

Outputs:
  FunctionUrl:
    Description: YELLCOP Endpoint
    Value:
      Fn::GetAtt: FunctionUrl.FunctionUrl

  FunctionArn:
    Description: YELLCOP ARN
    Value:
      Fn::GetAtt: Function.Arn

  FunctionIamRole:
    Description: YELLCOP IAM Role
    Value:
      Fn::GetAtt: FunctionRole.Arn
